-- this file is autogenerated by WowUp (app) at Tue Dec 29 2020 15:55:48 GMT+0100 (Mitteleuropäische Normalzeit)
local _, WOWUP = ...

WOWUP.addonManagerName = "WowUp"
WOWUP.addonManagerColorRGB = {232/255,205/255,134/255}
WOWUP.addonManagerNameSlashCommand = "/wowup"
WOWUP.updatesAvailableCount = 1
